Allow user accounts to use the API
tdlight-team/tdlight-telegram-bot-api pull request #18
Opened 2020-11-30 14:36 UTC by code1mountain

### User Mode

Enable user-mode with the command-line option `--user-mode`. User Mode is disabled by default.

You can now log into the bot api with user accounts to create userbots running on your account.
This functionality is currently in BETA.

Note: Never send your 2fa password over a plain http connection. Make sure https is enabled or use this api locally.

#### User Authorization Process
1. Create a random string with a length of `30 <= token_length <= 100`. This will work as your token and should not be 
   brute-forcible.

2. Send a request to `<api_url>/user<your_random_token>/login?phone_number=<your_phone_number>&password=<your_password>`
   The bot api will tell you to send the code then. The password parameter is optional.
   
3. Send the received code to `<api_url>/user<your_random_token>/authcode?code=12345`
   Will send ok on success. You are now logged in and can use all methods like in the bot api, just replace the 
   `/bot<token>/` in your urls with `/user<token>/`. If you do any mistakes during the authorization process,
   just create a new token and try again.
   
You only need to authenticate once, the account will stay logged in. You can use the `log_out` method to log out
or simply close the session in your account settings.

2020-11-30 14:44 UTC, andrew-ld commented
you should block all methods not available to normal users such as getcommands, setcommands, and various parameters in send(message, sticker, etc.) for example users cannot have an inline keyboard

2020-11-30 15:00 UTC, code1mountain commented
> you should block all methods not available to normal users such as getcommands, setcommands, and various parameters in send(message, sticker, etc.) for example users cannot have an inline keyboard

Okay, already had plans for this. btw getmycommands works for users, cause it just checks the full user info, but is alway an empty list.

2020-12-01 08:39 UTC, andrew-ld commented
I see that you have changed the indentation a lot, I suggest you use clang-format to make all the code standard

`find telegram-bot-api -name "*.cpp" -type f -exec clang-format {} \;`

2020-12-01 09:11 UTC, code1mountain commented
@andrew-ld I already undid the changes in a later commit. You can see it by reviewing the combined changes.

2020-12-01 09:38 UTC, giuseppeM99 commented on telegram-bot-api/Client.cpp
> +    CHECK(result->get_id() == 959899022);  // id for return type `seconds`
Please use `td_api::seconds::ID`

2020-12-01 16:17 UTC, iiiiii1wepfj commented
@code1mountain add methods only for users like join chat

2020-12-01 16:41 UTC, code1mountain commented
That's the plan. I'm going through the methods list of Pyrogram and implement all methods that make sense.

2020-12-01 16:46 UTC, iiiiii1wepfj commented
@code1mountain super noice

2020-12-01 21:32 UTC, Cavallium requested changes
Some lines are the same as the original code, but have the syntax changed. Please maintain them equal to the original branch.

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/HttpConnection.cpp
> +  }else{
Fix else spacing

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/HttpConnection.cpp
> +  }else{
Fix else spacing

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/Client.cpp
> +      //      return is_chat_member(supergroup_info->status);
Keep this line consistent with the source, since it's the same

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/Client.cpp
> +      file->local_->downloaded_size_ > MAX_DOWNLOAD_FILE_SIZE) {
Keep this line consistent with the source, since it's the same

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/Client.cpp
> +    ids.reserve(end - start + 1);
Keep this line consistent with the source, since it's the same

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/Client.cpp
> +  send_request(make_object<td_api::pingProxy>(), std::make_unique<TdOnPingCallback>(std::move(query)));
Keep this line consistent with the source, since it's the same

2020-12-01 21:32 UTC, Cavallium commented on telegram-bot-api/telegram-bot-api.cpp
> -  options.add_option('\0', "no-file-limit", "disable the file limits",
Keep this line consistent with the source, since it's the same

2020-12-02 13:17 UTC, code1mountain commented
@MarcoBuster Update: This Pull request will get closed soon. I'm working on a new implementation with an improved authorization process in a new branch that will come soon™. I will send a new Pull Request for that. The feedback for this functionality was really useful.

2020-12-02 13:27 UTC, mugavri commented
@code1mountain THANKS!

2020-12-02 13:33 UTC, MarcoBuster commented
> @MarcoBuster Update: This Pull request will get closed soon. I'm working on a new implementation with an improved authorization process in a new branch that will come soon™. I will send a new Pull Request for that. The feedback for this functionality was really useful.

Why would you create a new PR when you can use this one?

2020-12-04 22:00 UTC, giuseppeM99 commented
Development has been moved to #19

2020-12-04 22:00 UTC, closed without merging