Fix healtcheck fail when TELEGRAM_STAT is not set
tdlight-team/tdlight-telegram-bot-api pull request #50
Opened 2021-01-21 17:03 UTC by giuseppeM99

This should close #30 
plus this removes curl from the dependencies

2021-01-22 15:21 UTC, luckydonald requested changes
I think we can get rid of `|| exit 1` for now.

2021-01-22 15:23 UTC, giuseppeM99 commented on Dockerfile
> +HEALTHCHECK CMD nc -z localhost 8081 || exit 1
can you test it without `exit 1`? if that works i'll remove it [cc @MarcoBuster]

2021-01-22 18:07 UTC, MarcoBuster commented on Dockerfile
> +HEALTHCHECK CMD nc -z localhost 8081 || exit 1
@giuseppeM99, @luckydonald is right. 
```bash
marco@acer-pop:~$ nc 127.0.0.1 12345
marco@acer-pop:~$ echo $? 
1
```

2021-01-22 22:30 UTC, luckydonald commented
I tested the necat command with that, and it works.
Tested on a Mac, but is linux-y enough, most of the time.

LGTM

2021-01-22 22:30 UTC, luckydonald approved these changes
LGTM

2021-01-23 10:53 UTC, MarcoBuster approved these changes

2021-01-23 10:54 UTC, merged